global using AutoMapper;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using SB.Entity.Application.Dtos;
global using SB.Entity.Application.Implementations;
global using SB.Entity.Application.Implementations.Interfaces;
global using SB.Entity.Domain;
global using SB.Entity.Infrastructure.Cores;
global using SB.Entity.Infrastructure.Repositories.Interfaces;
global using SB.EXCEPTIONHANDLING.Dtos;
global using System.Reflection;
global using static SB.COMMONS.Constants;