global using Microsoft.IdentityModel.Tokens;
global using SB.TOKEN.APPLICATION.Dtos;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using SB.TOKEN.APPLICATION.Implementations;
global using SB.TOKEN.APPLICATION.Implementations.Interfaces;