global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using SB.Entity.Domain;
global using SB.Entity.Infrastructure.Configurations;
global using SB.Entity.Infrastructure.Cores;
global using SB.Entity.Infrastructure.Repositories;
global using SB.Entity.Infrastructure.Repositories.Interfaces;
